output "directory_id" {
  description = "AWS Managed Microsoft AD directory ID. Pass to aj-tf-module-vpn for Client VPN authentication."
  value       = aws_directory_service_directory.main.id
}

output "dns_ip_addresses" {
  description = "AD DNS server IP addresses. Used in DHCP options and Client VPN DNS configuration."
  value       = tolist(aws_directory_service_directory.main.dns_ip_addresses)
}

output "alias" {
  description = "AD directory alias — unique alias for the directory (auto-generated by AWS)."
  value       = aws_directory_service_directory.main.alias
}

output "security_group_id" {
  description = "Security group ID for the AD directory. Add to Client VPN and any resource that needs AD authentication."
  value       = aws_security_group.directory.id
}

output "admin_secret_arn" {
  description = "Secrets Manager ARN for the AD admin credentials. Use for break-glass access only."
  value       = aws_secretsmanager_secret.admin_password.arn
}

output "domain_name" {
  description = "FQDN of the AD domain (e.g. corp.platform.internal)."
  value       = aws_directory_service_directory.main.name
}

output "domain_short_name" {
  description = "NetBIOS short name of the AD domain (e.g. CORP)."
  value       = aws_directory_service_directory.main.short_name
}

output "dhcp_options_id" {
  description = "DHCP options set ID (null when enable_dhcp_options = false)."
  value       = var.enable_dhcp_options ? aws_vpc_dhcp_options.main[0].id : null
}
